"""
dqn_vs_montecarlo_sweep.py
============================
Loads a TRAINED DQN model (dqn_trained.pt) and evaluates it head-to-head
against Monte Carlo and Fixed Timer, across all 27 Low/Medium/High traffic
tier combinations — the same sweep methodology as full_tier_sweep.py, with
DQN added as a third strategy.

FAIRNESS NOTE: confirmed before building this that the DQN action space
(55 splits, generated by traffic_env.py's generate_actions()) and Monte
Carlo's candidate space (55 splits, generated by the same step/min-green
math) are IDENTICAL sets. Neither strategy has access to options the
other doesn't — a genuinely fair comparison, not an apples-to-oranges one.

Requires: pip install torch
Requires: dqn_trained.pt (the trained model file) in the same directory,
          or pass a different path via --model

Run:
    python3 dqn_vs_montecarlo_sweep.py
"""

import random
import itertools
import argparse

import torch

from traffic_env import TrafficEnv, ACTIONS, NUM_ACTIONS, NUM_LANES, CYCLE_BUDGET_SECONDS, SECONDS_PER_CAR
from dqn_agent import QNetwork

# ----------------------------------------------------------------------
# CONFIG (mirrors full_tier_sweep.py for direct comparability)
# ----------------------------------------------------------------------

MIN_GREEN_SECONDS = 5
TRIALS_PER_CANDIDATE = 200
SEARCH_STEP_SECONDS = 5
NUM_CYCLES_PER_RUN = 30

TIERS = {"LOW": 0.15, "MED": 0.30   , "HIGH": 0.45}
TIER_NAMES = list(TIERS.keys())
SEEDS_PER_COMBO = [101, 202, 303, 404, 505]
STARTING_QUEUES = [4, 2, 3]


# ----------------------------------------------------------------------
# SHARED SIMULATION PRIMITIVES (identical math to full_tier_sweep.py)
# ----------------------------------------------------------------------

def poisson_sample(lam, rng):
    L = pow(2.718281828, -lam)
    k = 0
    p = 1.0
    while True:
        k += 1
        p *= rng.random()
        if p <= L:
            return k - 1


def generate_candidate_splits(num_lanes, budget, min_green, step):
    candidates = []
    remaining = budget - (min_green * num_lanes)
    for extra_a in range(0, remaining + 1, step):
        for extra_b in range(0, remaining - extra_a + 1, step):
            extra_c = remaining - extra_a - extra_b
            if extra_c < 0:
                continue
            candidates.append([min_green + extra_a, min_green + extra_b, min_green + extra_c])
    return candidates


def pregenerate_trial_arrivals(num_trials, rng, arrival_rate_per_lane):
    trials = []
    for _ in range(num_trials):
        trial_arrivals = [
            poisson_sample(arrival_rate_per_lane[lane] * CYCLE_BUDGET_SECONDS, rng)
            for lane in range(NUM_LANES)
        ]
        trials.append(trial_arrivals)
    return trials


def simulate_one_trial(queue_lengths, green_split, precomputed_arrivals):
    total_remaining = 0
    for lane in range(NUM_LANES):
        queue = queue_lengths[lane]
        max_cleared = green_split[lane] / SECONDS_PER_CAR
        cleared = min(queue, max_cleared)
        after_clearing = queue - cleared
        total_remaining += after_clearing + precomputed_arrivals[lane]
    return total_remaining


def score_candidate(queue_lengths, green_split, shared_trials):
    total = 0
    for trial_arrivals in shared_trials:
        total += simulate_one_trial(queue_lengths, green_split, trial_arrivals)
    return total / len(shared_trials)


def monte_carlo_best_split(queue_lengths, rng, arrival_rate_per_lane):
    candidates = generate_candidate_splits(NUM_LANES, CYCLE_BUDGET_SECONDS, MIN_GREEN_SECONDS, SEARCH_STEP_SECONDS)
    shared_trials = pregenerate_trial_arrivals(TRIALS_PER_CANDIDATE, rng, arrival_rate_per_lane)
    best_split, best_score = None, float("inf")
    for split in candidates:
        score = score_candidate(queue_lengths, split, shared_trials)
        if score < best_score:
            best_score, best_split = score, split
    return best_split


def fixed_split():
    each = (CYCLE_BUDGET_SECONDS // NUM_LANES // SEARCH_STEP_SECONDS) * SEARCH_STEP_SECONDS
    remainder = CYCLE_BUDGET_SECONDS - each * (NUM_LANES - 1)
    return [each] * (NUM_LANES - 1) + [remainder]


def dqn_best_split(queue_lengths, q_network, state_scale=50.0):
    """Greedy DQN action selection — same normalization the agent was
    trained with (see dqn_agent.py's DQNAgent.STATE_SCALE)."""
    normalized = [q / state_scale for q in queue_lengths]
    with torch.no_grad():
        state_tensor = torch.tensor(normalized, dtype=torch.float32).unsqueeze(0)
        q_values = q_network(state_tensor)
        action_index = int(torch.argmax(q_values, dim=1).item())
    return ACTIONS[action_index]


def apply_cycle(queue_lengths, green_split, rng, arrival_rate_per_lane):
    new_queues = []
    total_cleared = 0
    for lane in range(NUM_LANES):
        queue = queue_lengths[lane]
        max_cleared = green_split[lane] / SECONDS_PER_CAR
        cleared = min(queue, max_cleared)
        after_clearing = queue - cleared
        expected_arrivals = arrival_rate_per_lane[lane] * CYCLE_BUDGET_SECONDS
        new_arrivals = poisson_sample(expected_arrivals, rng)
        new_queue = after_clearing + new_arrivals
        new_queues.append(new_queue)
        total_cleared += cleared
    return new_queues, total_cleared


# ----------------------------------------------------------------------
# RUN ONE (strategy, combo, seed)
# ----------------------------------------------------------------------

def run_one_combination(strategy, arrival_rate_per_lane, seed, q_network=None):
    decision_rng = random.Random(seed * 7919)
    outcome_rng = random.Random(seed)
    queues = list(STARTING_QUEUES)

    total_left_waiting = 0
    for _ in range(NUM_CYCLES_PER_RUN):
        if strategy == "montecarlo":
            split = monte_carlo_best_split(queues, decision_rng, arrival_rate_per_lane)
        elif strategy == "dqn":
            split = dqn_best_split(queues, q_network)
        else:  # fixed
            split = fixed_split()

        new_queues, _ = apply_cycle(queues, split, outcome_rng, arrival_rate_per_lane)
        total_left_waiting += sum(new_queues)
        queues = new_queues

    return total_left_waiting / NUM_CYCLES_PER_RUN


# ----------------------------------------------------------------------
# FULL SWEEP
# ----------------------------------------------------------------------

def run_full_sweep(q_network):
    all_combos = list(itertools.product(TIER_NAMES, repeat=NUM_LANES))
    assert len(all_combos) == 27

    results = []
    for combo in all_combos:
        rates = [TIERS[t] for t in combo]

        mc_waits, dqn_waits, fixed_waits = [], [], []
        for seed in SEEDS_PER_COMBO:
            mc_waits.append(run_one_combination("montecarlo", rates, seed))
            dqn_waits.append(run_one_combination("dqn", rates, seed, q_network))
            fixed_waits.append(run_one_combination("fixed", rates, seed))

        mc_avg = sum(mc_waits) / len(mc_waits)
        dqn_avg = sum(dqn_waits) / len(dqn_waits)
        fixed_avg = sum(fixed_waits) / len(fixed_waits)

        mc_improve = (fixed_avg - mc_avg) / fixed_avg * 100 if fixed_avg > 0 else 0
        dqn_improve = (fixed_avg - dqn_avg) / fixed_avg * 100 if fixed_avg > 0 else 0
        dqn_vs_mc = (mc_avg - dqn_avg) / mc_avg * 100 if mc_avg > 0 else 0

        results.append({
            "combo": combo, "mc_avg": mc_avg, "dqn_avg": dqn_avg, "fixed_avg": fixed_avg,
            "mc_improve": mc_improve, "dqn_improve": dqn_improve, "dqn_vs_mc": dqn_vs_mc,
        })
    return results


def print_report(results):
    print("=" * 100)
    print("  DQN vs MONTE CARLO vs FIXED TIMER — Full 27-Combination Sweep")
    print("  (DQN using your trained model's actual weights, greedy policy)")
    print("=" * 100)
    header = (f"{'Pattern':>16} | {'Fixed':>9} | {'MC':>9} | {'DQN':>9} | "
              f"{'MC vs Fix':>9} | {'DQN vs Fix':>10} | {'DQN vs MC':>9}")
    print(header)
    print("-" * len(header))
    for r in results:
        pattern = "/".join(r["combo"])
        print(f"{pattern:>16} | {r['fixed_avg']:>9.1f} | {r['mc_avg']:>9.1f} | {r['dqn_avg']:>9.1f} | "
              f"{r['mc_improve']:>8.1f}% | {r['dqn_improve']:>9.1f}% | {r['dqn_vs_mc']:>8.1f}%")
    print("-" * len(header))

    avg_mc = sum(r["mc_improve"] for r in results) / len(results)
    avg_dqn = sum(r["dqn_improve"] for r in results) / len(results)
    avg_dqn_vs_mc = sum(r["dqn_vs_mc"] for r in results) / len(results)

    print(f"\n  AVERAGES ACROSS ALL 27 COMBINATIONS:")
    print(f"    Monte Carlo vs Fixed Timer: {avg_mc:.1f}% improvement")
    print(f"    DQN vs Fixed Timer:         {avg_dqn:.1f}% improvement")
    print(f"    DQN vs Monte Carlo:         {avg_dqn_vs_mc:.1f}% "
          f"({'DQN better' if avg_dqn_vs_mc > 0 else 'Monte Carlo better'})")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="dqn_trained.pt", help="Path to trained model weights")
    parser.add_argument("--hidden-size", type=int, default=64,
                         help="Must match the hidden_size your model was actually trained with "
                              "(check what you passed to DQNAgent(...) in train_dqn.py)")
    args = parser.parse_args()

    q_network = QNetwork(state_dim=3, num_actions=NUM_ACTIONS, hidden_size=args.hidden_size)
    q_network.load_state_dict(torch.load(args.model, map_location="cpu"))
    q_network.eval()
    print(f"Loaded trained model from {args.model}\n")

    results = run_full_sweep(q_network)
    print_report(results)


if __name__ == "__main__":
    main()